#! /bin/sh
# asf_learn (Bourne shell script) -- Advanced Spam Filtering's learning script
# Learns from a given user's "learn-spam" & "learn-notspam" folders
#
# Usage: asf_learn [-d] <username>
#
# Note: this script must be run as the user given as <username>
# The cron job that calls this script should redirect stdout to a WRITABLE log file
#
# Version: 1.2.1

self=${0##*/}
syslog_facility=mail
syslog_tag="$self[$$]"

. /usr/local/etc/asf/conf.sh


# *** Functions ***
dir_empty()
{
  if [ "$(ls -A "$1")" ]; then
    return 1
  else
    return 0
  fi
}


# *** MAINLINE ***
# check for -d (the debug switch)
if [ x"$1" = x-d ] ; then
  shift
  log()
  {
    log_level=$1
    shift
    echo "$self($log_level): $*"
  }
else
  log()
  {
    log_level=$1
    shift
    logger -t $syslog_tag -p $syslog_facility.$log_level "$*"
  }
fi


if [ -n "$1" ] ; then
  username=$1
else
  echo "$self: no username supplied" >&2
  exit 1
fi

user_homedir=$(getent passwd $username | cut -d: -f6) 
if [ ! -d $user_homedir ] ; then
  echo "$self: invalid user '$username'" >&2
  exit 2
fi

if [ ! -d "$user_homedir/Maildir/.$LEARN_SPAM_FOLDER/cur" ] ; then
  echo "$self: \"~$username/Maildir/.$LEARN_SPAM_FOLDER\" doesn't exist" >&2
  exit 3
fi

if [ ! -d "$user_homedir/Maildir/.$LEARN_NOTSPAM_FOLDER/cur" ] ; then
  echo "$self: \"~$username/Maildir/.$LEARN_NOTSPAM_FOLDER\" doesn't exist" >&2
  exit 3
fi

echo "$(date --rfc-3339=seconds)  $username"

# Provide a stamp so that only files older than it are learned by
# asf_cleanup
touch "$user_homedir/Maildir/.$LEARN_SPAM_FOLDER/asf_learned"

# Check the user's training folders.  The user might or might not have
# viewed them since moving a message there, so check both the "new" and
# "cur" subdirectory for each.
for subdir in new cur ; do
  if ! dir_empty "$user_homedir/Maildir/.$LEARN_SPAM_FOLDER/$subdir"
  then
    log debug "spam for $username... learning"
    sa-learn --no-sync --spam "$user_homedir/Maildir/.$LEARN_SPAM_FOLDER/$subdir"
    sync=y
  fi
done
for subdir in new cur ; do
  if ! dir_empty "$user_homedir/Maildir/.$LEARN_NOTSPAM_FOLDER/$subdir"
  then
    log debug "ham for $username... learning"
    sa-learn --no-sync --ham "$user_homedir/Maildir/.$LEARN_NOTSPAM_FOLDER/$subdir"
    sync=y
    log debug "ham for $username... moving to inbox"
    mv $MV_OPTS "$user_homedir/Maildir/.$LEARN_NOTSPAM_FOLDER/$subdir"/* $user_homedir/Maildir/new
  fi
done

if [ "$sync" = y ] ; then
  log debug "syncing for $username"
  sa-learn --sync
fi

echo
log info "done for $username"
