#! /bin/sh
# setup_asf (Bourne shell script) -- sets up advanced spam filtering for a given user
#
# Version: 1.2

self=${0##*/}

set -e

. /usr/local/etc/asf/conf.sh

if [ -n "$1" ] ; then
  username=$1
else
  echo "$self: no username supplied" >&2
  exit 1
fi

user_homedir=$(getent passwd $username | cut -d: -f6) 
if [ ! -d $user_homedir ] ; then
  echo "$self: invalid user" >&2
  exit 2
fi

if [ ! -d $user_homedir/Maildir ] ; then
  echo "$self: ~$username/Maildir doesn't exist" >&2
  exit 2
fi

maildirmake.dovecot $user_homedir/Maildir/.$SPAM_FOLDER $username
maildirmake.dovecot $user_homedir/Maildir/.$LEARN_SPAM_FOLDER $username
maildirmake.dovecot $user_homedir/Maildir/.$LEARN_NOTSPAM_FOLDER $username

# this is used as a time boundary so asf_cleanup doesn't move spam that hasn't
# been learned yet
touch $user_homedir/Maildir/.$LEARN_SPAM_FOLDER/asf_learned

# check for "mailbox_command = procmail ..." in /etc/postfix/main.cf
if grep -q '^[[:space:]]*mailbox_command[[:space:]]*=[[:space:]]*[-a-z/]*procmail' /etc/postfix/main.cf
then
  echo "$self: Notice: /etc/postfix/main.cf already invokes procmail"
else
  if grep -q '^[^#]*procmail' $user_homedir/.forward 2>/dev/null
  then
    echo "$self: Notice: ~$username/.forward already invokes procmail" >&2
  else
    echo '"|exec /usr/bin/procmail"'>> $user_homedir/.forward
  fi
fi

echo
echo "Don't forget to create/update .procmailrc, replacing '.spam' with '.$SPAM_FOLDER'"
